---
title: "Antecedentes"
---

Respaldo teórico y empírico de la investigación 

En las últimas décadas, Chile ha experimentado un acelerado proceso de envejecimiento demográfico, fenómeno evidenciado por la inversión de la pirámide de edades. Según los datos del  @institutonacionaldeestadisticas_resultados_, para el año 1992 el porcentaje de personas de 65 años o más era de 6,6%, cifra que en el 2024 aumentó a 14%. Paralelamente, se observa una disminución del porcentaje del grupo etario de 15 años o menos, de manera que para el año 1992 la cifra era 29,4%, y para el año 2024 fue de 17,7%. Además, según el último Censo del año 2024, el índice de envejecimiento señala que hay 79 personas de 65 años o más por cada 100 menores de 15 años [@institutonacionaldeestadisticas_resultados_]. Asimismo, según las proyecciones realizadas por el Informe NODO (2021), estiman que en Chile en 2030 un cuarto de sus habitantes tendrá más de 60 años.

A este proceso, se suma la feminización del envejecimiento y de los cuidados, ya que según el Censo (2024), hay una mayor proporción de mujeres en edades avanzadas con un 56%. Además, la vejez femenina se caracteriza por tener ingresos inferiores a los hombres de la misma edad y realizar trabajo independiente y de cuidado principalmente (Gonzálvez, 2018).

Desde el punto de vista de salud, los adultos mayores tienen altas probabilidades de padecer enfermedades discapacitantes y neurodegenerativas, pero por el envejecimiento poblacional hay pocos miembros jóvenes de su red social que los puedan asistir [@tartaglini_trastornos_2012]. Estudios recientes indican que gran parte de las mujeres no tienen la educación primaria completa y enfrentan situaciones de salud complejas, con una alta prevalencia de enfermedades crónicas no transmisibles (ENT) [@bragato_avos_2023]. Esto, a su vez, genera problemas de salud asociados a la intensidad del trabajo de cuidados, dado que estas labores requieren una exigencia y desempeño que sobrepasan las capacidades de los adultos mayores [@santiagoorria_adultos_2022]. Así, el rol de cuidador informal presenta altos niveles de estrés, lo que ocasiona fisiopatologías y comportamientos poco saludables, que en conjunto contribuyen al desarrollo de enfermedades cardiovasculares, metabólicas, desregulaciones inmunológicas y trastornos psicofisiológicos [@tartaglini_trastornos_2012].

En términos económicos, según el informe NODO (2021), para el año 2019, las personas mayores contribuyeron con el 20.6% del trabajo no remunerado realizado por la población de 15 años y más. Agregan que el valor per cápita del trabajo no remunerado que hace esta población “equivale a 4,21 millones de pesos anuales, y es mayor al aporte per cápita de cualquier otra actividad económica”, además, este trabajo es realizado principalmente por mujeres, quienes aportan un 70.1% del valor económico total de este trabajo.

En relación al tiempo dedicado al trabajo no remunerado, la Encuesta Nacional del Uso del Tiempo (ENUT) del año 2015 muestra que la tasa de participación en este tipo de actividades para adultos mayores de 66 años y más corresponde al 93%. Estas actividades se distribuyen principalmente en tareas domésticas, tareas de cuidado y actividades comunitarias y que son realizadas principalmente por mujeres.

Por último, el envejecimiento poblacional ha generado modificaciones en las familias, de modo tal que la pluralidad de composiciones familiares, presenta un gran desafío para las políticas públicas en materia de salud, cuidados y protección social. El rol del adulto mayor en la dinámica familiar se ha hecho más relevante, en el cual cumplen labores de trabajo doméstico, de cuidados e incluso contribuciones económicas [@bragato_avos_2023]. En este contexto, según el informe NODO (2021), la Convención Interamericana sobre la Protección de los Derechos Humanos de las Personas Mayores, promulgada por Chile en 2017, constituye un gran avance en esta materia, ya que los estados se comprometen a valorar a las personas mayores y su papel en la sociedad. No obstante, aún persisten desafíos para garantizar un reconocimiento formal a los adultos mayores que realizan trabajo no remunerado, además, de incluir políticas con enfoque de género, que mejoren las condiciones de las principales contribuidoras del trabajo no remunerado.
