---
title: "El adulto mayor que cuida: la carga y relación con su bienestar"
number-sections: false
numbered: false
format:
  html:
    title-block-style: none
    toc: false
  pdf:
    title-block-style: none
---

::: {.content-visible when-format="pdf"}
\small\textbf{Palabras clave:} adultos mayores, trabajo de cuidados no remunerado, bienestar subjetivo, satisfacción con la vida, género, Chile.
\normalsize
:::

::: {.content-visible when-format="html"}
<style>
nav#TOC { display: none !important; }
div[data-when-format="pdf"] { display: none !important; }
</style>
<span class="keywords-line"><strong>Palabras clave:</strong> adultos mayores, trabajo de cuidados no remunerado, bienestar subjetivo, satisfacción con la vida, género, Chile. </span>
:::

# Abstract {.unnumbered}

Este estudio analiza la relación entre la carga de trabajo de cuidados no remunerados realizado por adultos mayores (60 años o más) y su bienestar objetivo, bienestar subjetivo y satisfacción con la vida en Chile. Utilizando datos de la II Encuesta Nacional del Uso del Tiempo [@__a], con una muestra de 10.099 observaciones, se calcularon correlaciones de Pearson y Spearman para contrastar tres hipótesis de asociación negativa. Los resultados muestran que en la muestra general existe una correlación positiva y de intensidad mediana entre horas de trabajo de cuidados no remunerado y bienestar objetivo ($r = 0.468$, $p < 0.01$), relación que se vuelve negativa pero no significativa al filtrar por el subgrupo de cuidadores ($r = -0.055$, $p = 0.09$). Por otro lado, se confirma una asociación negativa y estadísticamente significativa entre la carga de cuidados y el bienestar subjetivo de los cuidadores ($r = -0.207$, $p < 0.01$), así como con la satisfacción con la vida ($r = -0.070$, $p < 0.05$). Al segregar por sexo, la brecha de género es marcada: las mujeres mayores asumen una carga que promedia más del doble de tiempo que la de los hombres; además, tanto en mujeres como en hombres cuidadores se ratifican correlaciones negativas y significativas de la carga de cuidados con el bienestar subjetivo ($r = -0.198$, $p < 0.01$ y $r = -0.157$, $p < 0.05$, respectivamente), mientras que las correlaciones con la satisfacción con la vida, aunque también negativas ($r = -0.053$ y $r = -0.104$ respectivamente), no resultan estadísticamente significativas en ninguno de los dos subgrupos.